### PR TITLE
Fixed Svelte a11y warnings

### LINKED ISSUE #451: Fix svelte a11y warnings

### PR DESCRIPTION
**Pull request by saabi**
Closes #451

### CODE REVIEW

File: fe/src/routes/accessibility/+page.svelte [hunk 1]
```diff
@@ -150,7 +150,8 @@
 		padding: 2rem;
 	}
 
-	figure {
```
Comment (mindrones) [inline fe/src/routes/accessibility/+page.svelte:153]: I'd comment temporarily unused imports (`Bowser`,`Link`)

File: fe/src/lib/components/layout/medium/ThemeEditor.svelte [hunk 2]
```diff
@@ -51,10 +51,15 @@
 		{#each $_themeNames as name}
 			<li
 				class:selected={name === $_themeName}
-				on:click={() => {$_themeName = name}}
-				on:keydown={makeOnKeyDown(name)}
 			>
```
Comment (mindrones) [inline fe/src/lib/components/layout/medium/ThemeEditor.svelte]: I'd deindent if we have a single attribute

**Review by mindrones — APPROVED** [review]
Great, GTM!
